### ISSUE TITLE
Add examples to documentation

### ISSUE THREAD

**Issue by ricardograca** [MCProHosting/connect-smart-redis#1]
I think the documentation could use some examples explaining the basics. I never used the connect-redis module, so I wasn't aware what kind of extra modules were necessary (namely, `redis`) or how to setup the session store correctly. I managed to figure these things out by looking at the connect-redis docs, but it would be nice if the README in here provided all the necessary help for newcomers.

**Comment by connor4312** [comment]
Good idea, I'll do so now.

**Comment by ricardograca** [comment]
Nice :+1:
